// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdCWH247pLPVER3z23x0y_yH2tYof6uH0',
    appId: '1:711111911218:android:a853f8fa55c1bb48a4992b',
    messagingSenderId: '711111911218',
    projectId: 'every-rupee',
    storageBucket: 'every-rupee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-A92AYo8YfhdzqhzEe3cQxMNDO3SNZaA',
    appId: '1:711111911218:ios:e2ad603f5e3670a4a4992b',
    messagingSenderId: '711111911218',
    projectId: 'every-rupee',
    storageBucket: 'every-rupee.firebasestorage.app',
    androidClientId: '711111911218-agduuov41rp06mdopr7epb6h9jfnl978.apps.googleusercontent.com',
    iosClientId: '711111911218-50k55i8j9nc6psijouf5c4ufiv61u00t.apps.googleusercontent.com',
    iosBundleId: 'com.everyrupee.app',
  );

}